FROM postgres:15

# Optional: Kopieren Sie Ihre eigenen Initialisierungs-Skripte in das Image
# COPY ./init-db.sh /docker-entrypoint-initdb.d/

ENV POSTGRES_USER postgres
ENV POSTGRES_DB postgres

EXPOSE 5432