FROM python:3.8

WORKDIR /app

COPY ./DataConnectors/InfluxDataConnector/requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY ./commonRessources ./commonRessources
COPY ./DataConnectors/InfluxDataConnector .

CMD python /app/initInflux.py; python /app/app.py
