# PostgresDataConnector Development Dockerfile
# Used for development purposes only.
# Uses the flask werkzeug development server which is not suitable for production
FROM python:3.8

WORKDIR /app

COPY ./DataConnectors/PostgresDataConnector/requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY ./commonRessources ./commonRessources
COPY ./DataConnectors/PostgresDataConnector/ /app/

CMD python /app/initPostgres.py; python /app/app.py
