FROM python:3.8

WORKDIR /app
COPY ./Scheduler/requirements.txt  /app
RUN pip install -r requirements.txt
RUN pip install gunicorn

COPY ./commonRessources ./commonRessources
COPY ./Scheduler .

EXPOSE 5000

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]
