FROM python:3.8

WORKDIR /app

COPY ./Scheduler/requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY ./commonRessources ./commonRessources
COPY ./Scheduler .

CMD ["python", "app.py"]