services:
  frontend:
    build:
      context: ./Frontend/
    ports:
      - "80:80"
  
  dataconnector:
    build:
      context: ./DataConnector/
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=postgres

  scheduler:
    build:
      context: ./Scheduler/
      dockerfile: Dockerfile.${ENV}
    ports:
      - "5001:5000"
    depends_on:
      - dataconnector

  database:
    build:
      context: ./Database/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"