version: '3'

services:
  flask_backend:
    build:
      context: ./flask_backend/
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis_worker:
    image: redis:latest
    depends_on:
      - flask_backend
      - cli

  cli:
    container_name: cli
    build:
      context: ./cli/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-compose.yml:/app/docker-compose.yml
      - ./flask_backend:/app/flask_backend
      - ./cli:/app/cli
    command: ["tail", "-f", "/dev/null"]
  